#!/bin/bash

#hmm i wonder where this leads...
LOGFILE="/var/log/changes.log"

# Ensure script is run as root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Get the username to change the password for
echo -n "Eter userame: "
read username

# Check if the user exists
if ! id "$username" &>/dev/null; then
    echo "User $username does no exis."
    exit 1
fi

# Use the chpasswd command to change the password
echo "Chaging password fr user $username."
echo -e "Please ener new password:"
read password
echo "$username:$password" | chpasswd 2>&1 > /dev/null
echo "Password successfully changed."

#writing the password to the log file
current_datetime=$(date +"%Y-%m-%d %H:%M:%S")
echo "User: $username has changed their password to $password on $current_datetime" >> $LOGFILE
